import test from "node:test"; import assert from "node:assert/strict"; import { join } from "node:path"; import { fileURLToPath } from "node:url"; import { AppServerClient } from "../src/client.mjs";
const fixture = join(fileURLToPath(new URL("../fixtures/fake-server.mjs", import.meta.url)));
function client(mode, options = {}) { return new AppServerClient({ executable: process.execPath, args: [fixture, mode], requestTimeoutMs: 1500, ...options }); }
test("handles fragmented responses and clean shutdown", async () => { const app = client("fragmented"); await app.start(); const result = await app.request("account/rateLimits/read"); assert.equal(result.rateLimits.primary.windowDurationMins, 300); assert.equal((await app.shutdown()).graceful, true); });
test("keeps malformed stdout isolated from valid JSON-RPC", async () => { const app = client("malformed"); await app.start(); assert.deepEqual(app.protocolErrors, ["invalid_json"]); assert.equal((await app.request("account/rateLimits/read")).rateLimits.limitId, "codex"); await app.shutdown(); });
test("drains and bounds stderr", async () => { const app = client("stderr-flood", { maxStderrBytes: 4096 }); await app.start(); assert.equal(Buffer.byteLength(app.stderr) <= 4096, true); assert.equal((await app.request("account/rateLimits/read")).rateLimits.secondary.windowDurationMins, 10080); await app.shutdown(); });
test("correlates concurrent JSON-RPC responses by request id", async () => { const app = client("normal"); await app.start(); const results = await Promise.all(Array.from({ length: 20 }, () => app.request("account/rateLimits/read"))); assert.equal(results.length, 20); assert.equal(results.every((result) => result.rateLimits.limitId === "codex"), true); assert.equal(app.pending.size, 0); await app.shutdown(); });
test("times out and removes an unanswered request", async () => { const app = client("normal", { requestTimeoutMs: 100 }); await app.start(); await assert.rejects(app.request("test/no-response"), /timed out/); assert.equal(app.pending.size, 0); await app.shutdown(); });
test("rejects handshake when child crashes", async () => { const app = client("crash"); await assert.rejects(app.start(), /app-server exited/); assert.equal(app.states.includes("exited"), true); });
test("force shutdown terminates a hanging process tree", async () => { const app = client("tree-hang"); await app.start(); const note = app.notifications.find((item) => item.method === "test/grandchild"); assert.ok(note?.params?.pid); const shutdown = await app.shutdown({ graceMs: 100 }); assert.equal(shutdown.graceful, false); await new Promise((resolve) => setTimeout(resolve, 100)); assert.throws(() => process.kill(note.params.pid, 0)); });
